# ML Preprocess
## Contents
- Load Data
- Data Information
- Classifying catagorical and numerican datasets
- Data Wrangling
- Label Encoding
- Scale Data
    - Standard Scaler
    - Normalize
- Save Clean Data

# Load Data

In [1]:
#importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats
import plotly.express as px
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler, Normalizer, StandardScaler, LabelEncoder
sns.set()
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import preprocessing
import plotly.graph_objects as go
import warnings
warnings.filterwarnings("ignore")

In [2]:
# importing script modules from ../scripts
# Adding scripts path
import sys, os
sys.path.insert(0, '../scripts/')
from data_preProcessing import data_preProcessing_script
from data_manipulator import DataCleaner
from data_exploration import exploration

In [3]:
df = pd.read_csv("../data/processed_incl_missing.csv")
df.head()

,game_key,campaign_id,type,width,height,creative_id,auction_id,browser_ts,geo_country,site_name,...,Serving Location(s),Black/white/audience list included?,Cost Centre,currency,Buy Rate (CPE),Volume Agreed,Gross Cost/Budget,Agency Fee,Percentage,Net Cost
0,adunit-facebook-conversational-commerce-phase-...,l5kk3r3,impression,0,0,x83byc8a,fd74243f-6606-4830-a0ef-dd12f66ec6f5,2021-01-01 19:55:20.291,Thailand,www.wuxiaworld.com,...,Singapore,No black/white/audience list for this campaign,SGP,USD,0.28,242185.0,67811.8,0,15.0,57640.03
1,adunit-facebook-conversational-commerce-phase-...,l5kk3r3,impression,0,0,x83byc8a,fd74243f-6606-4830-a0ef-dd12f66ec6f5,2021-01-01 19:55:20.298,Thailand,www.wuxiaworld.com,...,Singapore,No black/white/audience list for this campaign,SGP,USD,0.28,242185.0,67811.8,0,15.0,57640.03
2,adunit-facebook-conversational-commerce-phase-...,l5kk3r3,impression,0,0,tf2htrrm,b3af878b-fd1a-4c6f-91a2-4e3670d2fda5,2021-01-05 00:21:39.693,Thailand,www.prachachat.net,...,Singapore,No black/white/audience list for this campaign,SGP,USD,0.28,242185.0,67811.8,0,15.0,57640.03
3,adunit-facebook-conversational-commerce-phase-...,l5kk3r3,impression,0,0,x83byc8a,b7c22590-e784-43cf-874d-a661ad99601f,2021-01-06 09:30:44.188,Thailand,www.prachachat.net,...,Singapore,No black/white/audience list for this campaign,SGP,USD,0.28,242185.0,67811.8,0,15.0,57640.03
4,adunit-facebook-conversational-commerce-phase-...,l5kk3r3,impression,0,0,x83byc8a,b7c22590-e784-43cf-874d-a661ad99601f,2021-01-06 09:30:45.047,Thailand,www.prachachat.net,...,Singapore,No black/white/audience list for this campaign,SGP,USD,0.28,242185.0,67811.8,0,15.0,57640.03

# Data Information

In [4]:
preprocess = data_preProcessing_script(df)
preprocess.show_data_information()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99946 entries, 0 to 99945
Data columns (total 31 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   game_key                             99946 non-null  object
 1   campaign_id                          99946 non-null  object
 2   type                                 99946 non-null  object
 3   width                                99946 non-null  int64
 4   height                               99944 non-null  object
 5   creative_id                          99946 non-null  object
 6   auction_id                           99946 non-null  object
 7   browser_ts                           99946 non-null  object
 8   geo_country                          99946 non-null  object
 9   site_name                            99946 non-null  object
 10  platform_os                          99946 non-null  int64
 11  device_type                          99946 non-null  object
 12  browser                              99946 non-null  object
 13  campaign_name                        99946 non-null  object
 14  Submission Date                      99946 non-null  object
 15  Description                          99946 non-null  object
 16  Campaign Objectives                  99946 non-null  object
 17  kpis                                 99946 non-null  object
 18  Placement(s)                         99946 non-null  object
 19  startdate                            99946 non-null  object
 20  enddate                              99946 non-null  object
 21  Serving Location(s)                  99946 non-null  object
 22  Black/white/audience list included?  99946 non-null  object
 23  Cost Centre                          99946 non-null  object
 24  currency                             99946 non-null  object
 25  Buy Rate (CPE)                       99946 non-null  float64
 26  Volume Agreed                        99946 non-null  float64
 27  Gross Cost/Budget                    99946 non-null  float64
 28  Agency Fee                           99944 non-null  object
 29  Percentage                           99946 non-null  float64
 30  Net Cost                             99946 non-null  float64
dtypes: float64(5), int64(2), object(24)
memory usage: 23.6+ MB

In [5]:
print('unique column values')
df.apply(lambda x: len(x.unique())).sort_values(ascending=False).head(33)

unique column values

browser_ts                             99501
auction_id                             83071
site_name                               5779
creative_id                              312
game_key                                 180
campaign_id                               46
campaign_name                             46
browser                                   30
Submission Date                           27
Description                               27
startdate                                 22
enddate                                   21
Gross Cost/Budget                         17
Net Cost                                  16
Campaign Objectives                       15
Volume Agreed                             15
Serving Location(s)                       14
geo_country                               12
kpis                                       9
height                                     8
platform_os                                7
currency                                   7
Buy Rate (CPE)                             7
device_type                                5
Cost Centre                                5
Agency Fee                                 4
Percentage                                 3
width                                      3
type                                       3
Placement(s)                               3
Black/white/audience list included?        3
dtype: int64

# Classifying catagorical and numerical Datasets

In [6]:
# getting dataframe columns list
cols = df.columns.tolist()

In [7]:
# numerical values
num_cols = df._get_numeric_data().columns
num_cols

Index(['width', 'platform_os', 'Buy Rate (CPE)', 'Volume Agreed',
       'Gross Cost/Budget', 'Percentage', 'Net Cost'],
      dtype='object')

In [8]:
# catagorical values
list(set(cols) - set(num_cols))

['Campaign Objectives',
 'startdate',
 'currency',
 'type',
 'Placement(s)',
 'campaign_name',
 'enddate',
 'Agency Fee',
 'height',
 'device_type',
 'auction_id',
 'creative_id',
 'geo_country',
 'game_key',
 'Submission Date',
 'browser',
 'campaign_id',
 'site_name',
 'kpis',
 'Cost Centre',
 'Description',
 'Black/white/audience list included?',
 'Serving Location(s)',
 'browser_ts']

# Data Wrangling

In [9]:
df.head()

,game_key,campaign_id,type,width,height,creative_id,auction_id,browser_ts,geo_country,site_name,...,Serving Location(s),Black/white/audience list included?,Cost Centre,currency,Buy Rate (CPE),Volume Agreed,Gross Cost/Budget,Agency Fee,Percentage,Net Cost
0,adunit-facebook-conversational-commerce-phase-...,l5kk3r3,impression,0,0,x83byc8a,fd74243f-6606-4830-a0ef-dd12f66ec6f5,2021-01-01 19:55:20.291,Thailand,www.wuxiaworld.com,...,Singapore,No black/white/audience list for this campaign,SGP,USD,0.28,242185.0,67811.8,0,15.0,57640.03
1,adunit-facebook-conversational-commerce-phase-...,l5kk3r3,impression,0,0,x83byc8a,fd74243f-6606-4830-a0ef-dd12f66ec6f5,2021-01-01 19:55:20.298,Thailand,www.wuxiaworld.com,...,Singapore,No black/white/audience list for this campaign,SGP,USD,0.28,242185.0,67811.8,0,15.0,57640.03
2,adunit-facebook-conversational-commerce-phase-...,l5kk3r3,impression,0,0,tf2htrrm,b3af878b-fd1a-4c6f-91a2-4e3670d2fda5,2021-01-05 00:21:39.693,Thailand,www.prachachat.net,...,Singapore,No black/white/audience list for this campaign,SGP,USD,0.28,242185.0,67811.8,0,15.0,57640.03
3,adunit-facebook-conversational-commerce-phase-...,l5kk3r3,impression,0,0,x83byc8a,b7c22590-e784-43cf-874d-a661ad99601f,2021-01-06 09:30:44.188,Thailand,www.prachachat.net,...,Singapore,No black/white/audience list for this campaign,SGP,USD,0.28,242185.0,67811.8,0,15.0,57640.03
4,adunit-facebook-conversational-commerce-phase-...,l5kk3r3,impression,0,0,x83byc8a,b7c22590-e784-43cf-874d-a661ad99601f,2021-01-06 09:30:45.047,Thailand,www.prachachat.net,...,Singapore,No black/white/audience list for this campaign,SGP,USD,0.28,242185.0,67811.8,0,15.0,57640.03

In [10]:
df.columns

Index(['game_key', 'campaign_id', 'type', 'width', 'height', 'creative_id',
       'auction_id', 'browser_ts', 'geo_country', 'site_name', 'platform_os',
       'device_type', 'browser', 'campaign_name', 'Submission Date',
       'Description', 'Campaign Objectives', 'kpis', 'Placement(s)',
       'startdate', 'enddate', 'Serving Location(s)',
       'Black/white/audience list included?', 'Cost Centre', 'currency',
       'Buy Rate (CPE)', 'Volume Agreed', 'Gross Cost/Budget', 'Agency Fee',
       'Percentage', 'Net Cost'],
      dtype='object')

In [11]:
# columns_with_large_missing_values_extracted_from_json
columns_to_drop = ['game_key', 'campaign_id', 'creative_id', 'auction_id', 'campaign_name', 'height', 'width', 
                   'Submission Date', 'Description', 'Campaign Objectives', 'Black/white/audience list included?', 'Agency Fee']

In [12]:
df_copy = df.drop(columns_to_drop, axis=1)

In [13]:
df_copy.head()

,type,browser_ts,geo_country,site_name,platform_os,device_type,browser,kpis,Placement(s),startdate,enddate,Serving Location(s),Cost Centre,currency,Buy Rate (CPE),Volume Agreed,Gross Cost/Budget,Percentage,Net Cost
0,impression,2021-01-01 19:55:20.291,Thailand,www.wuxiaworld.com,6,Mobile,Chrome,Engagement Rate,320x480 (Fullscreen mobile / interstitial)\n30...,2021-07-12,2021-09-08,Singapore,SGP,USD,0.28,242185.0,67811.8,15.0,57640.03
1,impression,2021-01-01 19:55:20.298,Thailand,www.wuxiaworld.com,6,Mobile,Mobile Safari UI/WKWebView,Engagement Rate,320x480 (Fullscreen mobile / interstitial)\n30...,2021-07-12,2021-09-08,Singapore,SGP,USD,0.28,242185.0,67811.8,15.0,57640.03
2,impression,2021-01-05 00:21:39.693,Thailand,www.prachachat.net,6,Mobile,Chrome Mobile,Engagement Rate,320x480 (Fullscreen mobile / interstitial)\n30...,2021-07-12,2021-09-08,Singapore,SGP,USD,0.28,242185.0,67811.8,15.0,57640.03
3,impression,2021-01-06 09:30:44.188,Thailand,www.prachachat.net,6,Mobile,Mobile Safari,Engagement Rate,320x480 (Fullscreen mobile / interstitial)\n30...,2021-07-12,2021-09-08,Singapore,SGP,USD,0.28,242185.0,67811.8,15.0,57640.03
4,impression,2021-01-06 09:30:45.047,Thailand,www.prachachat.net,6,Mobile,Chrome,Engagement Rate,320x480 (Fullscreen mobile / interstitial)\n30...,2021-07-12,2021-09-08,Singapore,SGP,USD,0.28,242185.0,67811.8,15.0,57640.03

In [14]:
# getting dataframe columns list
cols = df_copy.columns.tolist()

In [15]:
# numerical values
num_cols = df_copy._get_numeric_data().columns
num_cols

Index(['platform_os', 'Buy Rate (CPE)', 'Volume Agreed', 'Gross Cost/Budget',
       'Percentage', 'Net Cost'],
      dtype='object')

In [16]:
# catagorical values
list(set(cols) - set(num_cols))

['enddate',
 'startdate',
 'browser',
 'currency',
 'device_type',
 'kpis',
 'site_name',
 'Cost Centre',
 'geo_country',
 'type',
 'Serving Location(s)',
 'Placement(s)',
 'browser_ts']

# Label Encoding

In [25]:
from sklearn.preprocessing import LabelEncoder

In [26]:
cols =['enddate',
 'Placement(s)',
 'Cost Centre',
 'geo_country',
 'site_name',
 'browser',
 'device_type',
 'type',
 'currency',
 'Serving Location(s)',
 'browser_ts',
 'startdate',
 'kpis','platform_os']
#
# Encode labels of multiple columns at once
#
df_copy[cols] = df_copy[cols].apply(LabelEncoder().fit_transform)
#
# Print head
#
df_copy.head()

,type,browser_ts,geo_country,site_name,platform_os,device_type,browser,kpis,Placement(s),startdate,enddate,Serving Location(s),Cost Centre,currency,Buy Rate (CPE),Volume Agreed,Gross Cost/Budget,Percentage,Net Cost
0,2,4654,8,5700,5,0,4,6,1,20,19,7,2,6,0.28,242185.0,67811.8,15.0,57640.03
1,2,4655,8,5700,5,0,19,6,1,20,19,7,2,6,0.28,242185.0,67811.8,15.0,57640.03
2,2,6196,8,4805,5,0,5,6,1,20,19,7,2,6,0.28,242185.0,67811.8,15.0,57640.03
3,2,6339,8,4805,5,0,18,6,1,20,19,7,2,6,0.28,242185.0,67811.8,15.0,57640.03
4,2,6340,8,4805,5,0,4,6,1,20,19,7,2,6,0.28,242185.0,67811.8,15.0,57640.03

# Scale Data

### Standard Scaler

In [28]:
scaler = DataCleaner(df_copy, deep=True)
normalizer = DataCleaner(df_copy, deep=True)

In [29]:
cols =['enddate',
 'Placement(s)',
 'Cost Centre',
 'geo_country',
 'site_name',
 'browser',
 'device_type',
 'type',
 'currency',
 'Serving Location(s)',
 'browser_ts',
 'startdate',
 'kpis', 'platform_os']

In [30]:
df_cc = df_copy.drop(cols, axis=1)

In [31]:
df_cc.head()

   Buy Rate (CPE)  Volume Agreed  Gross Cost/Budget  Percentage  Net Cost
0            0.28       242185.0            67811.8        15.0  57640.03
1            0.28       242185.0            67811.8        15.0  57640.03
2            0.28       242185.0            67811.8        15.0  57640.03
3            0.28       242185.0            67811.8        15.0  57640.03
4            0.28       242185.0            67811.8        15.0  57640.03

In [32]:
# Using StandardScaler to standardize the all columns
scale_list = df_cc.columns.to_list()
scaler.standardize_columns(scale_list)

,type,browser_ts,geo_country,site_name,platform_os,device_type,browser,kpis,Placement(s),startdate,enddate,Serving Location(s),Cost Centre,currency,Buy Rate (CPE),Volume Agreed,Gross Cost/Budget,Percentage,Net Cost
0,2,4654,8,5700,5,0,4,6,1,20,19,7,2,6,-2.824124,2.421746,-0.087472,0.968693,-0.172359
1,2,4655,8,5700,5,0,19,6,1,20,19,7,2,6,-2.824124,2.421746,-0.087472,0.968693,-0.172359
2,2,6196,8,4805,5,0,5,6,1,20,19,7,2,6,-2.824124,2.421746,-0.087472,0.968693,-0.172359
3,2,6339,8,4805,5,0,18,6,1,20,19,7,2,6,-2.824124,2.421746,-0.087472,0.968693,-0.172359
4,2,6340,8,4805,5,0,4,6,1,20,19,7,2,6,-2.824124,2.421746,-0.087472,0.968693,-0.172359
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99941,2,28636,5,5625,4,0,18,6,1,12,10,7,2,4,0.639446,-0.457034,-0.629410,0.968693,-0.640576
99942,2,28638,5,5625,4,0,18,6,1,12,10,7,2,4,0.639446,-0.457034,-0.629410,0.968693,-0.640576
99943,2,28640,5,5625,4,0,18,6,1,12,10,7,2,4,0.639446,-0.457034,-0.629410,0.968693,-0.640576
99944,1,28641,5,5625,4,0,18,6,1,12,10,7,2,4,0.639446,-0.457034,-0.629410,0.968693,-0.640576
99945,2,28647,5,5625,5,0,5,6,1,12,10,7,2,4,0.639446,-0.457034,-0.629410,0.968693,-0.640576

### Normalize

In [33]:
normalizer.normalize_column(scale_list)

,type,browser_ts,geo_country,site_name,platform_os,device_type,browser,kpis,Placement(s),startdate,enddate,Serving Location(s),Cost Centre,currency,Buy Rate (CPE),Volume Agreed,Gross Cost/Budget,Percentage,Net Cost
0,2,4654,8,5700,5,0,4,6,1,20,19,7,2,6,0.000001,0.938628,0.262816,0.000058,0.223394
1,2,4655,8,5700,5,0,19,6,1,20,19,7,2,6,0.000001,0.938628,0.262816,0.000058,0.223394
2,2,6196,8,4805,5,0,5,6,1,20,19,7,2,6,0.000001,0.938628,0.262816,0.000058,0.223394
3,2,6339,8,4805,5,0,18,6,1,20,19,7,2,6,0.000001,0.938628,0.262816,0.000058,0.223394
4,2,6340,8,4805,5,0,4,6,1,20,19,7,2,6,0.000001,0.938628,0.262816,0.000058,0.223394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99941,2,28636,5,5625,4,0,18,6,1,12,10,7,2,4,0.000008,0.770678,0.485527,0.000287,0.412698
99942,2,28638,5,5625,4,0,18,6,1,12,10,7,2,4,0.000008,0.770678,0.485527,0.000287,0.412698
99943,2,28640,5,5625,4,0,18,6,1,12,10,7,2,4,0.000008,0.770678,0.485527,0.000287,0.412698
99944,1,28641,5,5625,4,0,18,6,1,12,10,7,2,4,0.000008,0.770678,0.485527,0.000287,0.412698
99945,2,28647,5,5625,5,0,5,6,1,12,10,7,2,4,0.000008,0.770678,0.485527,0.000287,0.412698

# Save Clean Data

In [34]:
scaler = DataCleaner(scaler.df)
scaler.save_clean_data('../data/scaled_data.csv')

In [35]:
normalizer = DataCleaner(normalizer.df)
normalizer.save_clean_data('../data/norm_data.csv')